subplot(321)
ylabel('$p_i$ [Pa]','interpreter','latex')
subplot(322)
ylabel('$h_i$ [J/kg]','interpreter','latex')
subplot(323)
ylabel('$\rho_i$ [kg/$m^3$]','interpreter','latex')
subplot(324)
ylabel('$\dot{m}_{HP}$ [kg/s]','interpreter','latex')
subplot(325)
ylabel('$\dot{V}$ [$m^3$/s]','interpreter','latex')
xlabel('t [s]','interpreter','latex')
subplot(326)
ylabel('$\dot{Q}$ [W]','interpreter','latex')
xlabel('t [s]','interpreter','latex')

saveas(gcf,'guntner.png')